dashboard:
  image: dalareo/design-thinking
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/yourapp
   - ROOT_URL=http://yourapp.com
   # - MAIL_URL=smtp://some.mailserver.com:25

mongo:
  image: mongo:latest
